openapi: 3.0.0
info:
  title: "My API"
  description: "MP DEI API"
  version: "0.0.1"
servers:
  - url: "/api"
paths:
  /sample:
    get:
      operationId: "sample.read"
      tags:
        - "Sample"
      summary: "Sample description"
      responses:
        "200":
          description: "Successfully used sample endpoint"
  /keyword-endpoint:
    post:
      operationId: "keyword_endpoint.create"
      tags:
        - "Keyword"
      summary: "Create a new keyword on the keyword table"
      requestBody:
        description: "Keyword to add"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                keyword:
                  type: string
              required:
                - id
                - keyword
      responses:
        "201":
          description: "Keyword created successfully"
        "400":
          description: "Invalid input"
