openapi: 3.0.0
info:
  title: "My API"
  description: "MP DEI API"
  version: "0.0.1"
servers:
  - url: "/api"
paths:
  /sample:
    get:
      operationId: "sample.read"
      tags:
        - "Sample"
      summary: "Sample description"
      responses:
        "200":
          description: "Successfully used sample endpoint"
