openapi: 3.0.0
info:
  title: "My API"
  description: "MP DEI API"
  version: "0.0.1"
servers:
  - url: "/api"
paths:
  /sample:
    get:
      operationId: "sample.read"
      tags:
        - "Sample"
      summary: "Sample description"
      responses:
        "200":
          description: "Successfully used sample endpoint"
  /keyword-endpoint:
    post:
      operationId: "keyword_endpoint.create"
      tags:
        - "Keyword"
      summary: "Create a new keyword on the keyword table"
      requestBody:
        description: "Keyword to add"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                keyword:
                  type: string
              required:
                - id
                - keyword
      responses:
        "201":
          description: "Keyword created successfully"
        "400":
          description: "Invalid input"
    get:
      operationId: "keyword_endpoint.get_popular"
      tags:
        - "Keyword"
      summary: "Get top-10 popular keywords between given years"
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: integer
          description: "Start year (inclusive)"
        - name: endDate
          in: query
          required: true
          schema:
            type: integer
          description: "End year (inclusive)"
      responses:
        "200":
          description: "Successfully retrieved top-10 popular keywords"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    keywordName:
                      type: string
                    publicationsCount:
                      type: integer
  /faculty-top-cited/{year}:
    get:
      operationId: "faculty.get_top_cited"
      tags:
        - "Faculty"
      summary: "Get top cited faculty"
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1000
            maximum: 9999
      responses:
        "200":
          description: "List of top cited faculty"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    faculty_id:
                      type: integer
                    faculty_name:
                      type: string
                    num_publications:
                      type: integer
        "400":
          description: "Invalid input"
        "500":
          description: "Database error"
