
name: Lint

on:
  pull_request:
    branches:
    - main
    - staging
    - 'release/**'
jobs:
  lint_flake8_vulture_black_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Linting & Tests
        run: |
          pip install -r dev-requirements.txt
          flake8 myapi/
          vulture myapi/
          black myapi/ --check